###
GET http://localhost:5000
###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"dwadad",
    "password":"12d45"
}
###
### Register a user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "gilesh@gmail.com",
    "password": "123123123"
}
